---

settings_application:
  dconf:
    debian:
      - { "key": "/com/ubuntu/sound/allow-amplified-volume", "value": "false" }

  gsettings:
    debian:
      - user: dkafetzi
        settings:
          - { "schema": "org.gnome.desktop.input-sources",          "key": "per-window",       "value": "false" }
          - { "schema": "org.gnome.desktop.input-sources",          "key": "sources",          "value": "[('xkb', 'us'), ('xkb', 'gr')]" }
          - { "schema": "org.gnome.gedit.plugins.filebrowser",      "key": "tree-view",        "value": "true" }
          - { "schema": "org.gnome.shell",                          "key": "favorite-apps",    "value": "['org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'code.desktop', 'firefox.desktop', 'firefox-trunk.desktop']" }
          - { "schema": "org.gnome.shell.extensions.desktop-icons", "key": "show-trash",       "value": "true" }
          - { "schema": "org.gnome.shell.extensions.desktop-icons", "key": "icon-size",        "value": "'small'" }
          - { "schema": "org.gnome.shell.extensions.desktop-icons", "key": "show-home",        "value": "true" }
          - { "schema": "org.yorba.shotwell.preferences.ui",        "key": "use-dark-theme",   "value": "true" }
          - { "schema": "org.yorba.shotwell.preferences.ui",        "key": "display-sidebar",  "value": "true" }
          - { "schema": "org.yorba.shotwell.preferences.ui",        "key": "display-toolbar",  "value": "true" }
          - { "schema": "org.yorba.shotwell.preferences.ui",        "key": "sidebar-position", "value": "180" }
          - { "schema": "org.yorba.shotwell.preferences.ui",        "key": "use-24-hour-time", "value": "true" }

  dot_files:
    debian:

      - user: root
        directories:
          - { "path": "/etc/profile.d",    "mode": '0755' }

        templates:
          - { "src": "profile.d.golang.j2", "dest": "/etc/profile.d/.golang.profile.sh", "owner": "root", "group": "root", "mode": '0644' }
          - { "src": "10-wakeup.rules.j2",  "dest": "/etc/udev/rules.d/10-wakeup.rules", "owner": "root", "group": "root", "mode": '0644' }

      - user: admin
        directories:
          - { "path": "/home/admin/logs",    "mode": '0700' }
          - { "path": "/home/admin/scripts", "mode": '0700' }

        templates:
          - { "src": "sudoers.d.admin.j2", "dest": "/etc/sudoers.d/99-admin-passwordless", "owner": "root", "group": "root", "mode": '0440', "validate": "/usr/sbin/visudo -cf %s" }

      - user: dkafetzi
        directories:
          - { "path": "/home/dkafetzi/.bashrc.d",         "mode": '0700' }
          - { "path": "/home/dkafetzi/.config",           "mode": '0700' }
          - { "path": "/home/dkafetzi/.config/Code",      "mode": '0700' }
          - { "path": "/home/dkafetzi/.config/Code/User", "mode": '0700' }
          - { "path": "/home/dkafetzi/.config/nvim",      "mode": '0700' }
          - { "path": "/home/dkafetzi/.ssh",              "mode": '0700' }
          - { "path": "/home/dkafetzi/workspace",         "mode": '0755' }
          - { "path": "/home/dkafetzi/workspace/go",      "mode": '0755' }

        templates:
          - { "src": "bash_profile.dkafetzi.j2",          "dest": "/home/dkafetzi/.bash_profile",                    "mode": '0700' }
          - { "src": "bashrc_common.dkafetzi.j2",         "dest": "/home/dkafetzi/.bashrc.d/.common.bashrc",         "mode": '0700' }
          - { "src": "bashrc_autocompletion.dkafetzi.j2", "dest": "/home/dkafetzi/.bashrc.d/.autocompletion.bashrc", "mode": '0700' }
          - { "src": "bashrc_aliases.dkafetzi.j2",        "dest": "/home/dkafetzi/.bashrc.d/.aliases.bashrc",        "mode": '0700' }
          - { "src": "gitconfig.dkafetzi.j2",             "dest": "/home/dkafetzi/.gitconfig",                       "mode": '0700' }
          - { "src": "inputrc.dkafetzi.j2",               "dest": "/home/dkafetzi/.inputrc",                         "mode": '0700' }
          - { "src": "profile.dkafetzi.j2",               "dest": "/home/dkafetzi/.profile",                         "mode": '0700' }
          - { "src": "ssh.config.dkafetzi.j2",            "dest": "/home/dkafetzi/.ssh/config",                      "mode": '0700' }
          - { "src": "vimrc.dkafetzi.j2",                 "dest": "/home/dkafetzi/.vimrc",                           "mode": '0700' }
          - { "src": "vscode.settings.json.dkafetzi.j2",  "dest": "/home/dkafetzi/.config/Code/User/settings.json",  "mode": '0700' }

  vscode:
    - user: dkafetzi
      extentions:
        - ms-azuretools.vscode-docker

  # Each command should output "Changed" to stdout so the task reports it as changed.
  custom:
    debian:
      - user: dkafetzi
        commands:
        # https://github.com/LunarVim/Neovim-from-scratch
        # If it is not the repository we want, delete everything and clone ours.
        # If it is the repository we want, clone it.
        # If there is no repository, delete everything and clone ours.
        - |
          if [[ $(cd /home/dkafetzi/.config/nvim; git remote get-url origin 2>/dev/null || true) == "git@github.com:amolofos/Neovim-from-scratch.git" ]]; then
            cd /home/dkafetzi/.config/nvim
            git pull origin bugfix/tree-sitter-ensure_installed
            git checkout bugfix/tree-sitter-ensure_installed
          else
            cd /home/dkafetzi/.config/ && rm -rf nvim
            git clone git@github.com:amolofos/Neovim-from-scratch.git /home/dkafetzi/.config/nvim
            cd /home/dkafetzi/.config/nvim
            git checkout bugfix/tree-sitter-ensure_installed
          fi

        # NerdFonts for neovim
        # https://www.lunarvim.org/configuration/04-nerd-fonts.html
        - |
          mkdir -p /home/dkafetzi/.local/share/fonts
          cd /home/dkafetzi/.local/share/fonts && curl -fLo "Droid Sans Mono for Powerline Nerd Font Complete.otf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf

          # And now we want to set the terminal font preferences.
          # https://askubuntu.com/questions/906137/seriously-dconf-gconf-gsettings-how-do-i-save-my-terminal-settings?noredirect=1&lq=1
          gprofile=$(gsettings get org.gnome.Terminal.ProfilesList default)
          gprofile=${gprofile:1:-1}
          gschema=org.gnome.Terminal.Legacy.Profile
          gpath=/org/gnome/terminal/legacy/profiles:/:${gprofile}/
          gsettings list-recursively ${gschema}:${gpath}
          gsettings set ${gschema}:${gpath} use-system-font false
          gsettings set ${gschema}:${gpath} font "DroidSansMono Nerd Font 10"
          gsettings list-recursively ${gschema}:${gpath}

      - user: admin
        commands:
          # This is needed for NerdFonts installation. See above.
          - sudo fc-cache -f -v
