---

software:
  pip:
    various:
      packages:
        - ansible-lint
        - pip
        - pipenv
        - psutil
        - pynvim
        - requests
        - setuptools
        - xmltodict
        - yamllint
