---

- name: Ensure kubectx repository is cloned from GitHub
  git:
    repo: "{{ source_url }}/{{ github_namespace }}"
    dest: "{{ kubectx_installation_path }}"
    version: "{{ kubectx_version }}"
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Ensure kubectx and kubens links are created
  file:
    src: "{{ kubectx_installation_path }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop: "{{ asset_name }}"
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
