---

extends: default

rules:
  braces:
    max-spaces-inside: -1

  commas:
    # Disable check for space after commas so that we can align our values visually.
    max-spaces-after: -1

  line-length:
    max: 160
