---

- name: "Install pip packages of software for {{ title }}"
  ansible.builtin.pip:
    name: "{{ packages | list }}"
    state: "latest"  # noqa package-latest
    extra_args: "--ignore-installed"
  when:
    - packages is defined
    - packages | length > 0
