---

- name: Set timezone
  register: test_out
  timezone:
    name: "{{ system.timezone }}"
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    # timedatectl command does not work inside docker...
    - not are_we_in_docker
