---

- assert:
    that:
      - action is defined
      - action in action_valid_options
    fail_msg: "'action' parameter is not defined"
    quiet: true

- include: pre-install-debian.yml
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# No need to pass any variables. They are already defined by the caller.
- include_role:
    name: system/software

- include: post-install-debian.yml
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
