---

# External dependencies.
automated_workstation_name:                 "{{ secret.automated_workstation_name }}"
automated_workstation_repository:           "{{ secret.automated_workstation_repository }}"
automated_workstation_repository_local_dir: "{{ secret.automated_workstation_repository_local_dir }}"
automated_workstation_secrets_repository:   "{{ secret.automated_workstation_secrets_repository }}"
automated_workstation_secrets_local_dir:    "{{ secret.automated_workstation_secrets_local_dir }}"

external_protected_secrets_dir:  "{{ automated_workstation_secrets_local_dir }}"
external_protected_secrets_env:  "{{ automated_workstation_name }}"
external_protected_secrets_file: "vault.yml"
external_protected_secrets_ext:  "yml"
