---

# Configuration.
config:
  system:
    locale: "en_GB.UTF-8"
    language: "en_GB.UTF-8"
    timezone: "Asia/Singapore"
  package_manager:
    cache_time: 3600
  software:
    common_list:
      - build-essential
      - curl
      - bzip2
      - colortest
      - diffutils
      - gcc
      - git
      - grep
      - gzip
      - htop
      - less
      - make
      - nano
      - nmap
      - openssl
      - p7zip
      - pwgen
      - rsync
      - software-properties-common
      - sshfs
      - sshpass
      - tar
      - tmux
      - unzip
      - vim
      - wget
      - whois
      - zip
    java:
      - default-jdk
      - default-jre
      - openjdk-11-jdk
      - openjdk-8-jdk
    java_alternative_location: "/usr/lib/jvm/java-11-openjdk-amd64/bin/java"

    #python:
#
    #go:
