# -----------------------------------------------------------------------------
# This is based on
#  * https://github.com/lvancrayelynghe/ansible-ubuntu/blob/master/roles/common/tasks/main.yml
#  * https://github.com/tzutalin/ubuntu-ansible/blob/master/roles/repo-over-https/tasks/main.yml
#
# -----------------------------------------------------------------------------
---

- assert:
    that:
      - action is defined
      - action in action_valid_options
    fail_msg: "'action' parameter is not defined"
    quiet: true

- include: "{{ action }}-debian.yml"
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include_role:
    name: system/software
  vars:
    action: update_cache
