# -----------------------------------------------------------------------------
# This is based on
#  * https://github.com/lvancrayelynghe/ansible-ubuntu/blob/master/roles/common/tasks/main.yml
#  * https://github.com/tzutalin/ubuntu-ansible/blob/master/roles/repo-over-https/tasks/main.yml
#
# -----------------------------------------------------------------------------
---

- name: Ensure the system can use the HTTPS transport for APT
  register: apt_https_transport
  stat:
    path: "/usr/lib/apt/methods/https"

- name: Install HTTPS transport for APT
  apt:
    pkg: apt-transport-https
    state: installed
  when:
    - not apt_https_transport.stat.exists

- name: Enable all repositories in sources.list
  become: yes
  replace:
    path: /etc/apt/sources.list
    regexp: '^#\s?deb(.+)http://(.+)/ubuntu(.+)$'
    replace: 'deb\1http://\2/ubuntu\3'
    backup: yes

- include_role:
    name: system/software
  vars:
    action: update_cache
