---

- name: Install latest version of software
  become: yes
  apt:
    pkg: "{{ software_list | default(software_list_default) }}"
    state: latest
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time | default(cache_valid_time_default) }}"
