---

- name: Install latest version of the distribution
  become: yes
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time | default(cache_valid_time_default) }}"
    force_apt_get: yes
