---

- name: Ensure kubectl is installed
  apt:
    name: "kubectl={{ kubectl_version }}-00"
    update_cache: true
    state: present
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
