---

- name: Update initramfs  # noqa fqcn-builtins
  register: update_initramfs_out
  become: true
  become_user: "root"
  shell: >-
    update-initramfs -u -k $(uname -r)
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: update-initramfs logs
  ansible.builtin.debug:
    msg: "{{ update_initramfs_out }}"
  changed_when: false
