---

# Gather facts
- import_playbook: tools-gather_facts.yml

# Install users  
- import_playbook: users.yml

## Install packages
#- import_playbook: essentials.yml
#
## Configure applications
#- import_playbook: editors.yml
#- import_playbook: source-control.yml
#- import_playbook: browsers.yml
#
## Install dot files
#- import_playbook: dotfiles.yml
#
## Configure desktop
#- import_playbook: desktop.yml