---

- import_playbook: tools-gather_facts.yml

- import_playbook: users.yml

- import_playbook: system-common.yml

- import_playbook: software-common.yml

- import_playbook: software-extra.yml

- import_playbook: software-development.yml

- import_playbook: users-dotfiles.yml

## Configure applications
#- import_playbook: editors.yml
#- import_playbook: source-control.yml

# Latex

## Configure desktop
#- import_playbook: desktop.yml
