---

- import_playbook: tools-gather_facts.yml

- import_playbook: users.yml

- import_playbook: system-localisation.yml

- import_playbook: system-package_manager.yml

- import_playbook: system-common-software.yml


- import_playbook: users-dotfiles.yml

## Configure applications
#- import_playbook: editors.yml
#- import_playbook: source-control.yml
#- import_playbook: browsers.yml


## Configure desktop
#- import_playbook: desktop.yml
