---

# Eclipse
# Rust
# Python

https://github.com/pascalgrimaud/ansible-ubuntu/tree/master/playbooks/roles
https://www.monodevelop.com/download/#fndtn-download-lin-ubuntu
https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu
