---

- name: Installing editors
  hosts: all
  roles:

    - name: editors/vi-and-vim
      when:
        - "{{ manage_vi_and_vim | default(true) | bool }}"

...
# Vi, vim, neovim
# Vs code
# Geany

# Add empty line
# Remove trailing space
# list, nu