---

- name: Apply user specific settings
  hosts: all
  roles:

    - role: utils/are_we_in_docker

    - role: settings/user
      when:
        - settings_user is defined

    - role: settings/application
      when:
        - settings_application is defined
