---

- name: Setup development software
  hosts: group_system
  tasks:

    - name: "TODO"
      debug:
        msg: "TODO"

# VsCode
# Git
# tmux
# openssh-server

# Virtualbox

# Docker
# Vagrant

# Pip packages
# Go
# Rust
# NodeJs

# Ansible
# Nomad
# Vault
# Consul
# Terraform
# Kubernetes
# memcached
# mysql
# sqlite

# AWS
# GCP
# Azure
# Openshift
