---

- name: Setup common software
  hosts: group_system
  tasks:

    - include_role:
        role: system/software
      vars:
        action: install_latest
        cache_valid_time: "{{ secret.config.package_manager.cache_time | default(config.package_manager.cache_time) }}"
        software_list: "{{ secret.config.software.common_list | default(config.software.common_list) }}"

    - include_role:
        role: system/software-java
      vars:
        action: install_latest
        cache_valid_time: "{{ secret.config.package_manager.cache_time | default(config.package_manager.cache_time) }}"
        software_list: "{{ secret.config.software.java | default(config.software.java) }}"
      when:
        - secret.config.software.java is defined or config.software.java is defined

    - include_role:
        role: system/software-python
      vars:
        action: install_latest
        cache_valid_time: "{{ secret.config.package_manager.cache_time | default(config.package_manager.cache_time) }}"
        software_list: "{{ secret.config.software.python | default(config.software.python) }}"
      when:
        - secret.config.software.python is defined or config.software.python is defined

# Vim and neoVim
