---

- name: Unattended software upgrade
  hosts: all
  roles:

    - role: software
      vars:
        state: upgrade
        cache_valid_time: "{{ package_manager.cache_valid_time }}"
      when:
        - software is defined

    - role: software
      vars:
        state: cleanup
