---

- name: Setup essentials
  hosts: group_system
  tasks:

    - include_role:
        role: system/package_manager
      vars:
        cache_valid_time: "{{ secret.config.package_manager.cache_time | default(config.package_manager.cache_time) }}"
