---

# Note that we expect the users to already exist in the system,
# as this role is very basic.

- name: Create users
  hosts: all
  roles:

    - role: utils/are_we_in_docker

    - role: system/user
      when:
        - users is defined
