---

- name: Applying gsettings
  include: gsettings.yml
  when:
    - settings_application.gsettings | length > 0

- name: Applying dconf
  include: dconf.yml
  when:
    - settings_application.dconf | length > 0

- name: Creating dot-files
  include: dot-files.yml
  when:
    - settings_application.dot_files | length > 0

- name: Handling vscode settings
  include: vscode.yml
  when:
    - settings_application.vscode | length > 0
