---

# settings_application:
#   vscode:
#    - user: dkafetzi
#      extentions: []
- name: Install vscode extentions  # noqa fqcn-builtins
  register: vscode_out
  become: true
  become_user: "{{ settings.0.user }}"
  shell: |
    code --install-extension {{ settings.1 }} --force
  args:
    executable: /bin/bash
    warn: false
  loop: "{{ settings_application.vscode | default([]) | subelements('extentions', skip_missing=True) }}"
  loop_control:
    loop_var: settings
  changed_when:
    - "'is already installed.' not in vscode_out.stdout or 'was successfully installed' in vscode_out.stdout"
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - not are_we_in_docker
